// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwC5pEhLdwM27q-KOEcUDtq57WzrIxII',
    appId: '1:798209874292:web:ea89d41c616316995cb421',
    messagingSenderId: '798209874292',
    projectId: 'fadaroapp',
    authDomain: 'fadaroapp.firebaseapp.com',
    storageBucket: 'fadaroapp.firebasestorage.app',
    measurementId: 'G-28KCB1ZKBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZeMgxjgh1MG6dtvEGuzXpr8qjDSrQe1M',
    appId: '1:798209874292:android:8ccc944386af8f4d5cb421',
    messagingSenderId: '798209874292',
    projectId: 'fadaroapp',
    storageBucket: 'fadaroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkqvDXx0wgpdDFSRm4Ex8hzBWTzMXTfUg',
    appId: '1:798209874292:ios:4469b030b28b038f5cb421',
    messagingSenderId: '798209874292',
    projectId: 'fadaroapp',
    storageBucket: 'fadaroapp.firebasestorage.app',
    androidClientId: '798209874292-6r7dqu1s8dk5stgi4km7rdjpesbetaqb.apps.googleusercontent.com',
    iosClientId: '798209874292-hqb7slvcn7ndb7s5q38101evfpuc6aef.apps.googleusercontent.com',
    iosBundleId: 'com.example.adaroappAdminPanel',
  );
}
